#!/bin/sh



# 設定ファイルに以下のように書き込んでください
# 接続先のサーバー情報
# server=hoge
#  
# テンプレートを置いておくディレクトリ
# templateDir=hoge
# templateName=hoge
# openDir=hoge
# secretDir=hoge




# 設定ファイルの読み込み
. ./setting/site_conf



#==================================
# functions
#==================================

temp(){

  #一時的なフォルダを作成する
  temp_file=$(mktemp)
  temp_dir=$(mktemp -d)
  trap "
  rm $temp_file
  rm -rf $temp_dir
  " 0

}

ls_dir(){

  #サーバー側のディレクトリを見る
  echo "
  ${1:-$secretDir}ディレクトリ
  ----------------------------
  "
  ssh $server command "cd ${1:-$secretDir};ls"
  echo "
  ----------------------------
  "

}

gitcall () {

  # template set up
  git clone ssh://$server/~/${templateDir}/${templateName} $1
  cd ./$1/
  rm -rf .git
  git init
  git add .
  git commit -m "First commit"

}


rm_site(){

  # サーバーにあるRepositoryを削除
  ssh $server command "
  cd ~/web/${openDir}/;
  rm -rf $1;
  cd ~/${secretDir}/;
  rm -rf $1"
  echo "${1}を削除しました。"

}

repository_setup(){

  # サーバーにRepositoryを追加
  ssh $server command "
  cd ~/${secretDir};
  mkdir ${1};
  cd ${1};
  git init --bare --shared;"
  ssh $server command "cd ~/${secretDir}/${1}/hooks;
cat << 'EOF' > post-receive
#!/bin/bash

cd ~/web/${openDir}/${1}
git --git-dir=.git pull origin develop:develop

EOF"
  ssh $server command "cd ~/${secretDir}/${1}/hooks;
  chmod 775 post-receive;
  "

  # サーバーの公開領域にRepositoryを追加
  ssh $server command "
  cd ~/web/${openDir};
  mkdir ${1};
  cd ${1};
  git init;
  git remote add origin ~/${secretDir}/${1}
  "
  echo "${1}を設定しました。
  url : http:basicexe.main.jp/${secretDir}/${1}/"

}

repository_add(){

  # リモートリポジトリtestを追加
  git remote add test ssh://${server}/~/${secretDir}/$1
  echo "リポジトリをtestとして追加しました。"

}



help(){
  echo "
  リポジトリの設定などセットアップを行うシェルスクリプトです。
  どのようなセットアップを行うか引数を入力してください。

  ［メニュー］

  リモートに公開します。　　　　　　　　　　　　  : rm
  テンプレートを呼び出します。　　　　　　　　　  : call
  テンプレートを呼び出してリモートに公開します。  : setup
  リモートを削除します。　　　　　　　　　        : all

  "
  ls_dir
}

#==================================
# 判定・処理
#==================================
case "$1" in
  "call")
    read -p "Please setup name: " fileName
    gitcall $fileName
    ;;
  "upload")
    ls_dir
    read -p "Please open file name : " fileName
    repository_setup $fileName
    repository_add $fileName
    ;;
  "setup")
    read -p "Please setup file name: " fileName
    gitcall $fileName
    repository_setup $fileName
    repository_add $fileName
    ;;
  "remove")
    ls_dir
    read -p "Please delete file neme : " template
    rm_site $template
    ls_dir
    ;;
  *)
    help
esac

