#!/bin/sh



# 設定ファイルに以下のように書き込んでください
# 接続先のサーバー情報
# server=hoge
#
# テンプレートを置いておくディレクトリ
# hostDir=hoge


# 設定ファイルの読み込み
. ~/.tools/setting/tools_conf



#==================================
# functions
#==================================

ls_dir(){

  #サーバー側のディレクトリを見る
  echo "
  ${1:-$hostDir}ディレクトリ
  ----------------------------
  "
  ssh $server command "cd ${1:-$hostDir};ls"
  echo "
  ----------------------------
  "

}

repository_setup(){

  # サーバーにRepositoryを追加
  ssh $server command "
  cd ~/${hostDir};
  mkdir ${1};
  cd ${1};
  git init --bare --shared;"

}

help(){
  echo "
  リポジトリの設定などセットアップを行うシェルスクリプトです。
  どのようなセットアップを行うか引数を入力してください。

  ［メニュー］

  リモートにリポジトリを登録します。　: add

  "
}

#==================================
# 判定・処理
#==================================
case "$1" in
  "add")
    read -p "Please setup name: " fileName
    repository_setup $fileName
    ;;
  *)
    help
esac

